[package]
name = "audio-stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.14.0"
anyhow = "1.0.65"
clap = "4.0.15"
hound = "3.5.0"